version: "3.8"
services:
  example:
    container_name: api
    build:
      context: ./
      dockerfile: Dockerfile-dev
    ports:
      - 5000:5000
    volumes:
      - .:/go/src/app:delegated
    environment:
      PORT: 5000
      FIRESTORE_EMULATOR_HOST: firestore:8812
      PROJECT_ID: project-id
    networks:
      - default
    depends_on:
      - database

  database:
    container_name: firestore
    build:
      context: ./
      dockerfile: Dockerfile-firestore
    environment:
      PROJECT_ID: project_id
    volumes:
      - ./firestore:/firestore
